"""Rule editor dialog. Adapts widget visibility to Simple / Expert mode."""
from __future__ import annotations

import hashlib
import re
from typing import Any

from PyQt6.QtCore import Qt
from PyQt6.QtGui import QFont
from PyQt6.QtWidgets import (
    QCheckBox,
    QComboBox,
    QDialog,
    QDialogButtonBox,
    QDoubleSpinBox,
    QFormLayout,
    QGroupBox,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QPlainTextEdit,
    QSplitter,
    QVBoxLayout,
    QWidget,
)

from hypr_wr_manager.rules import MatchSpec, Rule, exact_pattern, serialize_rule


_MATCH_MODES = ("Exact", "Substring", "Regex")
_FULLSCREEN_STATES = ("unset", "0", "1", "2")


def _slugify(s: str) -> str:
    s = re.sub(r"[^a-zA-Z0-9]+", "_", s).strip("_").lower()
    return s[:32] if s else "rule"


def suggest_name(client: dict[str, Any] | None, match: MatchSpec) -> str:
    seed = ""
    if client:
        seed = client.get("initialClass") or client.get("class") or client.get("title") or ""
    if not seed:
        seed = match.class_ or match.title or match.initial_class or match.initial_title or "rule"
    h = hashlib.sha1(seed.encode()).hexdigest()[:4]
    return f"hwr_{_slugify(seed)}_{h}"


class _ExpertMatchRow(QWidget):
    """A match row with enable-checkbox, label, mode combo, and line edit."""

    def __init__(self, label: str, initial_mode: str = "Exact") -> None:
        super().__init__()
        self.label = label
        self.enable = QCheckBox()
        self.mode = QComboBox()
        self.mode.addItems(_MATCH_MODES)
        self.mode.setCurrentText(initial_mode)
        self.edit = QLineEdit()
        self.edit.setPlaceholderText(f"{label} value")
        lbl = QLabel(label)
        lbl.setMinimumWidth(100)
        layout = QHBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.addWidget(self.enable)
        layout.addWidget(lbl, 0)
        layout.addWidget(self.mode, 0)
        layout.addWidget(self.edit, 1)

    def set_value(self, literal: str, *, checked: bool = True, mode: str = "Exact") -> None:
        self.enable.setChecked(checked)
        self.mode.setCurrentText(mode)
        self.edit.setText(literal)

    def rendered(self) -> str | None:
        if not self.enable.isChecked():
            return None
        value = self.edit.text()
        if not value:
            return None
        mode = self.mode.currentText()
        if mode == "Exact":
            return exact_pattern(value)
        return value

    def prefill_from_existing(self, stored: str) -> None:
        self.enable.setChecked(True)
        m = re.fullmatch(r"\^\((.+)\)\$", stored)
        if m:
            self.mode.setCurrentText("Exact")
            try:
                self.edit.setText(re.sub(r"\\(.)", r"\1", m.group(1)))
            except re.error:
                self.edit.setText(m.group(1))
            return
        self.mode.setCurrentText("Regex")
        self.edit.setText(stored)


class RuleEditorDialog(QDialog):
    def __init__(
        self,
        parent: QWidget | None = None,
        *,
        workspaces: list[dict[str, Any]] | None = None,
        client: dict[str, Any] | None = None,
        existing: Rule | None = None,
        expert: bool = False,
    ) -> None:
        super().__init__(parent)
        self.setWindowTitle("Edit rule" if existing else "New rule")
        self._workspaces = workspaces or []
        self._client = client
        self._existing = existing
        self._expert = expert

        self._build_ui()
        self._apply_mode_visibility()

        if existing is not None:
            self._load_from_rule(existing)
        elif client is not None:
            self._prefill_from_client(client)

        self._wire_change_signals()
        self._update_preview()

        # Size heuristic — simple mode fits nicely smaller.
        self.resize(820, 620 if expert else 520)

    # -- UI --------------------------------------------------------------

    def _build_ui(self) -> None:
        root = QVBoxLayout(self)

        # Name row
        name_row = QHBoxLayout()
        name_row.addWidget(QLabel("Name:"))
        self.name_edit = QLineEdit()
        self.name_edit.setPlaceholderText("hwr_<auto-generated>")
        name_row.addWidget(self.name_edit, 1)
        root.addLayout(name_row)

        splitter = QSplitter(Qt.Orientation.Horizontal)
        splitter.addWidget(self._build_match_pane())
        splitter.addWidget(self._build_properties_pane())
        splitter.setSizes([400, 450])
        root.addWidget(splitter, 1)

        # Live preview (expert only; hidden in simple)
        self._preview_label = QLabel("Preview (written verbatim to disk):")
        root.addWidget(self._preview_label)
        self.preview = QPlainTextEdit()
        self.preview.setReadOnly(True)
        font = QFont("monospace")
        font.setStyleHint(QFont.StyleHint.Monospace)
        self.preview.setFont(font)
        self.preview.setFixedHeight(160)
        root.addWidget(self.preview)

        buttons = QDialogButtonBox(
            QDialogButtonBox.StandardButton.Ok | QDialogButtonBox.StandardButton.Cancel
        )
        buttons.accepted.connect(self.accept)
        buttons.rejected.connect(self.reject)
        root.addWidget(buttons)

    # Match pane --------------------------------------------------------
    def _build_match_pane(self) -> QWidget:
        box = QGroupBox("Match")
        v = QVBoxLayout(box)

        # Simple-mode single match row:
        self.simple_row = QWidget()
        srl = QHBoxLayout(self.simple_row)
        srl.setContentsMargins(0, 0, 0, 0)
        self.simple_field = QComboBox()
        self.simple_field.addItem("class", userData="class")
        self.simple_field.addItem("title", userData="title")
        self.simple_edit = QLineEdit()
        self.simple_edit.setPlaceholderText("e.g. firefox")
        srl.addWidget(QLabel("Match:"))
        srl.addWidget(self.simple_field)
        srl.addWidget(self.simple_edit, 1)
        v.addWidget(self.simple_row)

        hint = QLabel(
            "<i>Simple mode matches the window class exactly (or a substring of its title). "
            "Switch to Expert for regex, initial_class, tags, and more.</i>"
        )
        hint.setWordWrap(True)
        hint.setStyleSheet("color: palette(mid);")
        self._simple_hint = hint
        v.addWidget(hint)

        # Expert-mode rows (hidden in simple):
        self.mf_initial_class = _ExpertMatchRow("initial_class", "Exact")
        self.mf_class = _ExpertMatchRow("class", "Exact")
        self.mf_initial_title = _ExpertMatchRow("initial_title", "Substring")
        self.mf_title = _ExpertMatchRow("title", "Substring")
        for mf in (self.mf_initial_class, self.mf_class, self.mf_initial_title, self.mf_title):
            v.addWidget(mf)

        self.tag_row = QWidget()
        tag_layout = QHBoxLayout(self.tag_row)
        tag_layout.setContentsMargins(0, 0, 0, 0)
        self.tag_enable = QCheckBox()
        self.tag_edit = QLineEdit()
        self.tag_edit.setPlaceholderText("tag name (no leading +)")
        tag_lbl = QLabel("match:tag")
        tag_lbl.setMinimumWidth(100)
        tag_layout.addWidget(self.tag_enable)
        tag_layout.addWidget(tag_lbl)
        tag_layout.addWidget(self.tag_edit, 1)
        v.addWidget(self.tag_row)

        self.fs_match_row = QWidget()
        fs_layout = QHBoxLayout(self.fs_match_row)
        fs_layout.setContentsMargins(0, 0, 0, 0)
        fs_lbl = QLabel("match:fullscreen")
        fs_lbl.setMinimumWidth(100)
        self.match_fullscreen = QComboBox()
        self.match_fullscreen.addItems(("unset", "true", "false"))
        fs_layout.addWidget(fs_lbl)
        fs_layout.addWidget(self.match_fullscreen)
        fs_layout.addStretch(1)
        v.addWidget(self.fs_match_row)

        v.addStretch(1)
        return box

    # Properties pane ---------------------------------------------------
    def _build_properties_pane(self) -> QWidget:
        container = QWidget()
        outer = QVBoxLayout(container)
        outer.setContentsMargins(0, 0, 0, 0)

        # Behavior box
        self.behavior_box = QGroupBox("Behavior")
        bform = QFormLayout(self.behavior_box)
        self.float_combo = QComboBox()
        self.float_combo.addItems(("unset", "on", "off"))
        bform.addRow("float", self.float_combo)
        self.center_combo = QComboBox()
        self.center_combo.addItems(("unset", "on", "off"))
        bform.addRow("center", self.center_combo)
        # expert-only rows:
        self.pin_combo = QComboBox()
        self.pin_combo.addItems(("unset", "on", "off"))
        self._pin_label = QLabel("pin")
        bform.addRow(self._pin_label, self.pin_combo)
        self.fullscreen_state = QComboBox()
        self.fullscreen_state.addItems(_FULLSCREEN_STATES)
        self._fs_state_label = QLabel("fullscreen")
        bform.addRow(self._fs_state_label, self.fullscreen_state)
        self.no_blur = QCheckBox("no_blur on")
        self._no_blur_label = QLabel("")
        bform.addRow(self._no_blur_label, self.no_blur)
        outer.addWidget(self.behavior_box)

        # Placement box
        self.placement_box = QGroupBox("Placement")
        pform = QFormLayout(self.placement_box)
        self.workspace_combo = QComboBox()
        self.workspace_combo.setEditable(True)
        self.workspace_combo.addItem("")
        for ws in self._workspaces:
            name = ws.get("name")
            wid = ws.get("id")
            if name and isinstance(wid, int) and wid > 0:
                self.workspace_combo.addItem(str(wid), userData=str(wid))
            elif name:
                self.workspace_combo.addItem(str(name), userData=str(name))
        pform.addRow("workspace", self.workspace_combo)
        self.size_edit = QLineEdit()
        self.size_edit.setPlaceholderText("e.g. 800 600  or  (monitor_w*0.7) (monitor_h*0.6)")
        pform.addRow("size", self.size_edit)
        outer.addWidget(self.placement_box)

        # Appearance box
        self.appearance_box = QGroupBox("Appearance")
        aform = QFormLayout(self.appearance_box)
        row = QHBoxLayout()
        self.opacity_enable = QCheckBox()
        self.opacity_active = QDoubleSpinBox()
        self.opacity_active.setRange(0.0, 1.0)
        self.opacity_active.setSingleStep(0.05)
        self.opacity_active.setDecimals(2)
        self.opacity_active.setValue(0.9)
        self.opacity_inactive_enable = QCheckBox("also inactive:")
        self.opacity_inactive = QDoubleSpinBox()
        self.opacity_inactive.setRange(0.0, 1.0)
        self.opacity_inactive.setSingleStep(0.05)
        self.opacity_inactive.setDecimals(2)
        self.opacity_inactive.setValue(0.8)
        row.addWidget(self.opacity_enable)
        row.addWidget(QLabel("active:"))
        row.addWidget(self.opacity_active)
        row.addSpacing(10)
        row.addWidget(self.opacity_inactive_enable)
        row.addWidget(self.opacity_inactive)
        row.addStretch(1)
        aform.addRow("opacity", row)
        outer.addWidget(self.appearance_box)

        outer.addStretch(1)
        return container

    # -- simple/expert toggle -------------------------------------------

    def _apply_mode_visibility(self) -> None:
        expert = self._expert
        # Match pane
        self.simple_row.setVisible(not expert)
        self._simple_hint.setVisible(not expert)
        for w in (
            self.mf_initial_class,
            self.mf_class,
            self.mf_initial_title,
            self.mf_title,
            self.tag_row,
            self.fs_match_row,
        ):
            w.setVisible(expert)
        # Behavior pane — hide pin, fullscreen_state, no_blur in simple
        for w in (
            self._pin_label,
            self.pin_combo,
            self._fs_state_label,
            self.fullscreen_state,
            self._no_blur_label,
            self.no_blur,
        ):
            w.setVisible(expert)
        # Appearance — inactive-opacity widgets hidden in simple
        self.opacity_inactive_enable.setVisible(expert)
        self.opacity_inactive.setVisible(expert)
        # Preview
        self._preview_label.setVisible(expert)
        self.preview.setVisible(expert)

    # -- signal wiring ---------------------------------------------------

    def _wire_change_signals(self) -> None:
        text_widgets = [
            self.name_edit,
            self.simple_edit,
            self.mf_initial_class.edit,
            self.mf_class.edit,
            self.mf_initial_title.edit,
            self.mf_title.edit,
            self.tag_edit,
            self.size_edit,
            self.workspace_combo.lineEdit(),
        ]
        for w in text_widgets:
            if w is not None:
                w.textChanged.connect(self._update_preview)

        for mf in (self.mf_initial_class, self.mf_class, self.mf_initial_title, self.mf_title):
            mf.enable.stateChanged.connect(self._update_preview)
            mf.mode.currentTextChanged.connect(self._update_preview)
        self.simple_field.currentTextChanged.connect(self._update_preview)
        self.tag_enable.stateChanged.connect(self._update_preview)
        self.match_fullscreen.currentTextChanged.connect(self._update_preview)
        self.float_combo.currentTextChanged.connect(self._update_preview)
        self.pin_combo.currentTextChanged.connect(self._update_preview)
        self.center_combo.currentTextChanged.connect(self._update_preview)
        self.fullscreen_state.currentTextChanged.connect(self._update_preview)
        self.no_blur.stateChanged.connect(self._update_preview)
        self.opacity_enable.stateChanged.connect(self._update_preview)
        self.opacity_inactive_enable.stateChanged.connect(self._update_preview)
        self.opacity_active.valueChanged.connect(self._update_preview)
        self.opacity_inactive.valueChanged.connect(self._update_preview)

    # -- prefill ---------------------------------------------------------

    def _prefill_from_client(self, c: dict[str, Any]) -> None:
        initial_class = c.get("initialClass") or ""
        cls = c.get("class") or ""
        initial_title = c.get("initialTitle") or ""
        title = c.get("title") or ""

        # Simple-mode prefill
        if cls:
            self.simple_field.setCurrentIndex(self.simple_field.findData("class"))
            self.simple_edit.setText(cls)
        elif initial_class:
            self.simple_field.setCurrentIndex(self.simple_field.findData("class"))
            self.simple_edit.setText(initial_class)
        elif title:
            self.simple_field.setCurrentIndex(self.simple_field.findData("title"))
            self.simple_edit.setText(title)

        # Expert-mode prefill (populated even if hidden, so toggling mode keeps context)
        if initial_class:
            self.mf_initial_class.set_value(initial_class, checked=True, mode="Exact")
        if cls and cls != initial_class:
            self.mf_class.set_value(cls, checked=not initial_class, mode="Exact")
        if initial_title:
            self.mf_initial_title.edit.setText(initial_title)
        if title and title != initial_title:
            self.mf_title.edit.setText(title)

        self.name_edit.setText(suggest_name(c, self._build_match_spec()))

    def _load_from_rule(self, rule: Rule) -> None:
        self.name_edit.setText(rule.name)
        m = rule.match
        if m.initial_class:
            self.mf_initial_class.prefill_from_existing(m.initial_class)
        if m.class_:
            self.mf_class.prefill_from_existing(m.class_)
        if m.initial_title:
            self.mf_initial_title.prefill_from_existing(m.initial_title)
        if m.title:
            self.mf_title.prefill_from_existing(m.title)
        # Simple mode: try to back-fill from whichever match exists.
        if m.class_:
            self.simple_field.setCurrentIndex(self.simple_field.findData("class"))
            self._unwrap_into(self.simple_edit, m.class_)
        elif m.title:
            self.simple_field.setCurrentIndex(self.simple_field.findData("title"))
            self._unwrap_into(self.simple_edit, m.title)
        if m.tag:
            self.tag_enable.setChecked(True)
            self.tag_edit.setText(m.tag)
        if m.fullscreen is True:
            self.match_fullscreen.setCurrentText("true")
        elif m.fullscreen is False:
            self.match_fullscreen.setCurrentText("false")

        if rule.float is True:
            self.float_combo.setCurrentText("on")
        elif rule.float is False:
            self.float_combo.setCurrentText("off")
        if rule.pin is True:
            self.pin_combo.setCurrentText("on")
        elif rule.pin is False:
            self.pin_combo.setCurrentText("off")
        if rule.center is True:
            self.center_combo.setCurrentText("on")
        elif rule.center is False:
            self.center_combo.setCurrentText("off")
        if rule.fullscreen_state:
            self.fullscreen_state.setCurrentText(rule.fullscreen_state)
        if rule.no_blur:
            self.no_blur.setChecked(True)
        if rule.workspace:
            idx = self.workspace_combo.findText(rule.workspace)
            if idx >= 0:
                self.workspace_combo.setCurrentIndex(idx)
            else:
                self.workspace_combo.setEditText(rule.workspace)
        if rule.size:
            self.size_edit.setText(rule.size)
        if rule.opacity:
            parts = rule.opacity.split()
            self.opacity_enable.setChecked(True)
            try:
                self.opacity_active.setValue(float(parts[0]))
            except (ValueError, IndexError):
                pass
            if len(parts) >= 2:
                self.opacity_inactive_enable.setChecked(True)
                try:
                    self.opacity_inactive.setValue(float(parts[1]))
                except ValueError:
                    pass

    @staticmethod
    def _unwrap_into(edit: QLineEdit, stored: str) -> None:
        m = re.fullmatch(r"\^\((.+)\)\$", stored)
        if m:
            try:
                edit.setText(re.sub(r"\\(.)", r"\1", m.group(1)))
                return
            except re.error:
                pass
        edit.setText(stored)

    # -- result ----------------------------------------------------------

    def _build_match_spec(self) -> MatchSpec:
        m = MatchSpec()
        if self._expert:
            m.initial_class = self.mf_initial_class.rendered()
            m.class_ = self.mf_class.rendered()
            m.initial_title = self.mf_initial_title.rendered()
            m.title = self.mf_title.rendered()
            if self.tag_enable.isChecked() and self.tag_edit.text():
                m.tag = self.tag_edit.text()
            fs = self.match_fullscreen.currentText()
            if fs == "true":
                m.fullscreen = True
            elif fs == "false":
                m.fullscreen = False
        else:
            field = self.simple_field.currentData() or "class"
            value = self.simple_edit.text().strip()
            if value:
                if field == "class":
                    m.class_ = exact_pattern(value)
                else:
                    m.title = value
        return m

    def build_rule(self) -> Rule:
        name = self.name_edit.text().strip()
        if not name:
            name = suggest_name(self._client, self._build_match_spec())
        rule = Rule(name=name, match=self._build_match_spec())
        if self.float_combo.currentText() == "on":
            rule.float = True
        elif self.float_combo.currentText() == "off":
            rule.float = False
        if self._expert:
            if self.pin_combo.currentText() == "on":
                rule.pin = True
            elif self.pin_combo.currentText() == "off":
                rule.pin = False
        if self.center_combo.currentText() == "on":
            rule.center = True
        elif self.center_combo.currentText() == "off":
            rule.center = False
        if self._expert:
            fs = self.fullscreen_state.currentText()
            if fs != "unset":
                rule.fullscreen_state = fs
            if self.no_blur.isChecked():
                rule.no_blur = True
        ws = self.workspace_combo.currentText().strip()
        if ws:
            rule.workspace = ws
        size = self.size_edit.text().strip()
        if size:
            rule.size = size
        if self.opacity_enable.isChecked():
            active = f"{self.opacity_active.value():.2f}".rstrip("0").rstrip(".")
            if self._expert and self.opacity_inactive_enable.isChecked():
                inactive = f"{self.opacity_inactive.value():.2f}".rstrip("0").rstrip(".")
                rule.opacity = f"{active} {inactive}"
            else:
                rule.opacity = active
        if self._existing is not None:
            rule.raw_extras = list(self._existing.raw_extras)
        return rule

    def _update_preview(self) -> None:
        if not self._expert:
            return  # preview hidden
        try:
            rule = self.build_rule()
            self.preview.setPlainText(serialize_rule(rule))
        except Exception as e:  # pragma: no cover — defensive UI path
            self.preview.setPlainText(f"# preview error: {e}")
